### ISSUE TITLE
OSError: [Errno 2] No such file or directory: 2017-12-29-BrowsingClassificationData_v0.1.0.ipynb

### ISSUE THREAD

**Issue by twongjirad** [DeepLearnPhysics/Blog#1]
pelican /home/twongjirad/working/dlphysics/Blog/content -o /home/twongjirad/working/dlphysics/Blog/output -s /home/twongjirad/working/dlphysics/Blog/pelicanconf.py 
WARNING: Caught Exception: OSError: [Errno 2] No such file or directory: '/home/twongjirad/working/dlphysics/Blog/content/2017-12-29-BrowsingClassificationData_v0.1.0.ipynb'
WARNING: Cannot get modification stamp for /home/twongjirad/working/dlphysics/Blog/content/./2017-12-29-BrowsingClassificationData_v0.1.0.ipynb
  | 	OSError: [Errno 2] No such file or directory: '/home/twongjirad/working/dlphysics/Blog/content/./2017-12-29-BrowsingClassificationData_v0.1.0.ipynb'
WARNING: Cannot get modification stamp for /home/twongjirad/working/dlphysics/Blog/content/2017-12-29-BrowsingClassificationData_v0.1.0.ipynb
  | 	OSError: [Errno 2] No such file or directory: '/home/twongjirad/working/dlphysics/Blog/content/2017-12-29-BrowsingClassificationData_v0.1.0.ipynb'
ERROR: Could not process ./2017-12-29-BrowsingClassificationData_v0.1.0.ipynb
  | OSError: [Errno 2] No such file or directory: '/home/twongjirad/working/dlphysics/Blog/content/2017-12-29-BrowsingClassificationData_v0.1.0.ipynb'
WARNING: _get_summary() has been deprecated since 3.6.4. Use the summary decorator instead
Done: Processed 4 articles, 0 drafts, 0 pages and 0 hidden pages in 1.76 seconds.

**Comment by twongjirad** [comment]
The missing file is only a broken softlink:

lrwxrwxrwx 1 twongjirad twongjirad   71 Dec 31 17:35 2017-12-29-BrowsingClassificationData_v0.1.0.ipynb -> /Users/kazuhiro/blog/2017-12-29-BrowsingClassificationData_v0.1.0.ipynb

**Comment by drinkingkazu** [comment]
Sorry! https://github.com/DeepLearnPhysics/Blog/commit/43634ad77e1e9edf66fb48cd492a7760e9c65a1f should fix this. Can you try and close if it works?

**Comment by drinkingkazu** [comment]
@twongjirad confirmed this is fixed.
